"""
This is a lazy way to avoid opening a json, simply import this file to extract scanner filter size.
This provides a scanner filter size that is needed to make the final image have a filter size of 8x8x8.
"""


sidecar_template_full = {
    "Modality": "",
    "Manufacturer": "",
    "ManufacturersModelName": "",
    "Units": "",
    "InstitutionName": "",
    "InstitutionAddress": "",
    "InstitutionalDepartmentName": "",
    "BodyPart": "",
    "TracerName": "",
    "TracerRadionuclide": "",
    "TracerRadionuclideHalflife": "",
    "InjectedRadioactivity": "",
    "InjectedRadioactivityUnits": "",
    "InjectedMass": "",
    "InjectedMassUnits": "",
    "SpecificRadioactivity": "",
    "SpecificRadioactivityUnits": "",
    "ModeOfAdministration": "",
    "TracerRadLex": "",
    "TracerSNOMED": "",
    "TracerMolecularWeight": "",
    "TracerMolecularUnits": "",
    "InjectedMassPerWeight": "",
    "InjectedMassPerWeightUnits": "",
    "SpecificRadioactivityMeasTime": "",
    "MolarActivity": "",
    "MolarActivityUnits": "",
    "MolarActivityMeasTime": "",
    "InfusionRadioActivity": "",
    "InfusionStart": "",
    "InfusionSpeed": "",
    "InfusionSpeedUnits": "",
    "InjectedVolume": "",
    "Purity": "",
    "PharamceuticalName": "",
    "PharmaceuticalDoseAmount": [],
    "PharmaceuticalDoseUnits": "",
    "PharmaceuticalDoseRegimen": "",
    "PharmaceuticalDoseTime": [],
    "Anaesthesia": "",
    "TimeZero": "",
    "ScanStart": "",
    "InjectionStart": "",
    "FrameTimesStart": [],
    "FrameDuration": [],
    "ScanDate": "",
    "InjectionEnd": "",
    "AcquisitionMode": "",
    "ImageDecayCorrected": "",
    "ImageDecayCorrectionTime": "",
    "ReconMethodName": "",
    "ReconMethodParameterLabels": [],
    "ReconMethodParameterUnits": [],
    "ReconMethodParameterValues": [],
    "ReconFilterType": [],
    "ReconFilterSize": [],
    "AttenuationCorrection": "",
    "ReconMethodImplementationVersion": "",
    "AttenuationCorrectionMethodReference": "",
    "ScaleFactor": [],
    "ScatterFraction": [],
    "DecayCorrectionFactor": [],
    "PromptRate": [],
    "RandomRate": [],
    "SinglesRate": []
}

sidecar_template_short = {
    "Modality": "",
    "Manufacturer": "",
    "ManufacturersModelName": "",
    "Units": "",
    "TracerName": "",
    "TracerRadionuclide": "",
    "TracerRadionuclideHalflife": "",
    "InjectedRadioactivity": "",
    "InjectedRadioactivityUnits": "",
    "InjectedMass": "",
    "InjectedMassUnits": "",
    "SpecificRadioactivity": "",
    "SpecificRadioactivityUnits": "",
    "ModeOfAdministration": "",
    "TimeZero": "",
    "ScanStart": "",
    "InjectionStart": "",
    "FrameTimesStart": [],
    "FrameDuration": [],
    "AcquisitionMode": "",
    "ImageDecayCorrected": "",
    "ImageDecayCorrectionTime": "",
    "ReconMethodName": "",
    "ReconMethodParameterLabels": [],
    "ReconMethodParameterUnits": [],
    "ReconMethodParameterValues": [],
    "ReconFilterType": [],
    "ReconFilterSize": [],
    "AttenuationCorrection": ""
}

sidecar_template_custom = {
    "Modality": "PT",
    "ImagingFrequency": 0,
    "Manufacturer": "Siemens",
    "ManufacturersModelName": "",
    "PatientPosition": "HFS",
    "ProcedureStepDescription": "",
    "SoftwareVersions": "",
    "SeriesDescription": "",
    "ProtocolName": "",
    "ImageType": [],
    "SeriesNumber": "",
    "AcquisitionTime": "",
    "Radiopharmaceutical": "",
    "RadionuclidePositronFraction": "",
    "RadionuclideTotalDose": "",
    "RadionuclideHalfLife": "",
    "DoseCalibrationFactor": "",
    "Units": "",
    "DecayCorrection": "",
    "AttenuationCorrectionMethod": "",
    "ReconstructionMethod": "",
    "DecayFactor": [],
    "FrameTimesStart": [],
    "FrameTimesStartUnits": "min",
    "FrameDuration": [],
    "FrameDurationUnits": "min",
    "FrameTimesEnd": [],
    "FrameTimesEndUnits": "min",
    "SliceThickness": "",
    "ImageOrientationPatientDICOM": [],
    "ConversionSoftware": "dcm2niix",
    "ConversionSoftwareVersion": ""
}
